# [SEQUENCE: 1] Prometheus configuration for game server monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    cluster: 'game-cluster'

# [SEQUENCE: 2] Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# [SEQUENCE: 3] Rule files
rule_files:
  - '/etc/prometheus/alerts.yml'

# [SEQUENCE: 4] Scrape configurations
scrape_configs:
  # [SEQUENCE: 5] Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # [SEQUENCE: 6] Game server instances
  - job_name: 'game-servers'
    static_configs:
      - targets: 
        - 'game-server-zone1:9090'
        - 'game-server-zone2:9090'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'game_server_.*'
        action: keep

  # [SEQUENCE: 7] Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # [SEQUENCE: 8] Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # [SEQUENCE: 9] PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres'

  # [SEQUENCE: 10] RabbitMQ exporter
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rabbitmq'

  # [SEQUENCE: 11] Kubernetes service discovery (for K8s deployment)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - mmorpg-game
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name