# [SEQUENCE: 1] ConfigMap for game server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-server-config
  namespace: mmorpg-game
  labels:
    app.kubernetes.io/name: game-server
    app.kubernetes.io/component: configuration
data:
  # [SEQUENCE: 2] Server configuration
  server.yaml: |
    server:
      name: "MMORPG Game Server"
      version: "1.0.0"
      
    network:
      game_port: 8080
      health_port: 8081
      metrics_port: 9090
      max_connections: 10000
      
    world:
      tick_rate: 30
      save_interval: 300
      
    logging:
      level: "${LOG_LEVEL}"
      format: "json"
      
    database:
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_NAME}"
      user: "${DB_USER}"
      
    redis:
      url: "${REDIS_URL}"
      
    rabbitmq:
      url: "${RABBITMQ_URL}"
      
  # [SEQUENCE: 3] Prometheus scrape configuration
  prometheus-config: |
    - job_name: 'game-servers'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - mmorpg-game
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2