########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(cli11_COMPONENT_NAMES "")
if(DEFINED cli11_FIND_DEPENDENCY_NAMES)
  list(APPEND cli11_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES cli11_FIND_DEPENDENCY_NAMES)
else()
  set(cli11_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(cli11_PACKAGE_FOLDER_RELEASE "/home/woopinbells/.conan2/p/cli11e4e4357835029/p")
set(cli11_BUILD_MODULES_PATHS_RELEASE )


set(cli11_INCLUDE_DIRS_RELEASE "${cli11_PACKAGE_FOLDER_RELEASE}/include")
set(cli11_RES_DIRS_RELEASE )
set(cli11_DEFINITIONS_RELEASE )
set(cli11_SHARED_LINK_FLAGS_RELEASE )
set(cli11_EXE_LINK_FLAGS_RELEASE )
set(cli11_OBJECTS_RELEASE )
set(cli11_COMPILE_DEFINITIONS_RELEASE )
set(cli11_COMPILE_OPTIONS_C_RELEASE )
set(cli11_COMPILE_OPTIONS_CXX_RELEASE )
set(cli11_LIB_DIRS_RELEASE )
set(cli11_BIN_DIRS_RELEASE )
set(cli11_LIBRARY_TYPE_RELEASE UNKNOWN)
set(cli11_IS_HOST_WINDOWS_RELEASE 0)
set(cli11_LIBS_RELEASE )
set(cli11_SYSTEM_LIBS_RELEASE )
set(cli11_FRAMEWORK_DIRS_RELEASE )
set(cli11_FRAMEWORKS_RELEASE )
set(cli11_BUILD_DIRS_RELEASE )
set(cli11_NO_SONAME_MODE_RELEASE FALSE)


# COMPOUND VARIABLES
set(cli11_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${cli11_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${cli11_COMPILE_OPTIONS_C_RELEASE}>")
set(cli11_LINKER_FLAGS_RELEASE
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${cli11_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${cli11_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${cli11_EXE_LINK_FLAGS_RELEASE}>")


set(cli11_COMPONENTS_RELEASE )