########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(sol2_COMPONENT_NAMES "")
if(DEFINED sol2_FIND_DEPENDENCY_NAMES)
  list(APPEND sol2_FIND_DEPENDENCY_NAMES lua)
  list(REMOVE_DUPLICATES sol2_FIND_DEPENDENCY_NAMES)
else()
  set(sol2_FIND_DEPENDENCY_NAMES lua)
endif()
set(lua_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(sol2_PACKAGE_FOLDER_RELEASE "/home/woopinbells/.conan2/p/sol23dff0da353939/p")
set(sol2_BUILD_MODULES_PATHS_RELEASE )


set(sol2_INCLUDE_DIRS_RELEASE "${sol2_PACKAGE_FOLDER_RELEASE}/include")
set(sol2_RES_DIRS_RELEASE )
set(sol2_DEFINITIONS_RELEASE )
set(sol2_SHARED_LINK_FLAGS_RELEASE )
set(sol2_EXE_LINK_FLAGS_RELEASE )
set(sol2_OBJECTS_RELEASE )
set(sol2_COMPILE_DEFINITIONS_RELEASE )
set(sol2_COMPILE_OPTIONS_C_RELEASE )
set(sol2_COMPILE_OPTIONS_CXX_RELEASE )
set(sol2_LIB_DIRS_RELEASE )
set(sol2_BIN_DIRS_RELEASE )
set(sol2_LIBRARY_TYPE_RELEASE UNKNOWN)
set(sol2_IS_HOST_WINDOWS_RELEASE 0)
set(sol2_LIBS_RELEASE )
set(sol2_SYSTEM_LIBS_RELEASE )
set(sol2_FRAMEWORK_DIRS_RELEASE )
set(sol2_FRAMEWORKS_RELEASE )
set(sol2_BUILD_DIRS_RELEASE )
set(sol2_NO_SONAME_MODE_RELEASE FALSE)


# COMPOUND VARIABLES
set(sol2_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${sol2_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${sol2_COMPILE_OPTIONS_C_RELEASE}>")
set(sol2_LINKER_FLAGS_RELEASE
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${sol2_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${sol2_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${sol2_EXE_LINK_FLAGS_RELEASE}>")


set(sol2_COMPONENTS_RELEASE )